import { SportCategory, Match, GradeScore, ClassRanking, Post, RankingItem } from './types';

export const SPORT_CATEGORIES: SportCategory[] = [
  { id: 'soccer', name: '축구', iconName: 'Trophy', category: '구기종목', totalPoints: 150, description: '전/후반 각 20분 11인제 축구 대진' },
  { id: 'basketball', name: '농구', iconName: 'Dumbbell', category: '구기종목', totalPoints: 120, description: '전반 15분 후반 15분 5대5 코트전' },
  { id: 'dodgeball', name: '피구', iconName: 'Flame', category: '구기종목', totalPoints: 100, description: '남녀 혼성 15인 피구 서바이벌' },
  { id: 'relay', name: '이어달리기(계주)', iconName: 'Zap', category: '육상', totalPoints: 200, description: '4x100m 학년 통합 대표 계주' },
  { id: 'tug_of_war', name: '줄다리기', iconName: 'Users', category: '민속/단체', totalPoints: 150, description: '30인 단체 3판 2선승제 파워 매치' },
  { id: 'badminton', name: '배드민턴', iconName: 'Activity', category: '구기종목', totalPoints: 80, description: '복식 토너먼트 21점 3세트제' },
  { id: 'esports', name: 'e스포츠(롤)', iconName: 'Gamepad2', category: 'e스포츠', totalPoints: 100, description: '소환사의 협곡 5:5 단판 승부' },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'm-1',
    sport: 'soccer',
    round: '결승',
    teamA: { name: '3-1 드래곤', grade: 3, classNum: 1, color: 'blue' },
    teamB: { name: '3-4 타이거', grade: 3, classNum: 4, color: 'white' },
    scoreA: 2,
    scoreB: 1,
    status: 'in_progress',
    time: '14:30',
    court: '중앙 대운동장 A코트',
    pointsForWinner: 150,
  },
  {
    id: 'm-2',
    sport: 'basketball',
    round: '결승',
    teamA: { name: '2-2 불스', grade: 2, classNum: 2, color: 'blue' },
    teamB: { name: '2-5 레이커스', grade: 2, classNum: 5, color: 'white' },
    scoreA: 34,
    scoreB: 32,
    status: 'in_progress',
    time: '14:40',
    court: '실내 체육관 1층',
    pointsForWinner: 120,
  },
  {
    id: 'm-3',
    sport: 'dodgeball',
    round: '결승',
    teamA: { name: '1-3 불꽃슛', grade: 1, classNum: 3, color: 'blue' },
    teamB: { name: '1-6 회오리', grade: 1, classNum: 6, color: 'white' },
    scoreA: 15,
    scoreB: 8,
    status: 'completed',
    winner: 'blue',
    time: '13:00',
    court: '보조 운동장 C구역',
    pointsForWinner: 100,
  },
  {
    id: 'm-4',
    sport: 'relay',
    round: '결승',
    teamA: { name: '청군 학년연합', grade: 3, classNum: 0, color: 'blue' },
    teamB: { name: '백군 학년연합', grade: 3, classNum: 0, color: 'white' },
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    time: '16:00 (피날레)',
    court: '중앙 트랙',
    pointsForWinner: 200,
  },
  {
    id: 'm-5',
    sport: 'tug_of_war',
    round: '4강',
    teamA: { name: '2-1 천하장사', grade: 2, classNum: 1, color: 'blue' },
    teamB: { name: '2-3 일기당천', grade: 2, classNum: 3, color: 'white' },
    scoreA: 2,
    scoreB: 0,
    status: 'completed',
    winner: 'blue',
    time: '11:20',
    court: '운동장 특설무대 앞',
    pointsForWinner: 100,
  },
  {
    id: 'm-6',
    sport: 'badminton',
    round: '4강',
    teamA: { name: '3-2 셔틀콕', grade: 3, classNum: 2, color: 'blue' },
    teamB: { name: '3-5 스매시', grade: 3, classNum: 5, color: 'white' },
    scoreA: 21,
    scoreB: 19,
    status: 'completed',
    winner: 'blue',
    time: '10:40',
    court: '체육관 B코트',
    pointsForWinner: 80,
  },
  {
    id: 'm-7',
    sport: 'esports',
    round: '결승',
    teamA: { name: '무선 페이커즈 (3-3)', grade: 3, classNum: 3, color: 'blue' },
    teamB: { name: '무선 쵸비즈 (2-4)', grade: 2, classNum: 4, color: 'white' },
    scoreA: 1,
    scoreB: 0,
    status: 'in_progress',
    time: '15:10',
    court: '컴퓨터실 및 방송실 중계',
    pointsForWinner: 100,
  },
];

export const INITIAL_GRADE_SCORES: GradeScore[] = [
  { grade: 1, blueScore: 380, whiteScore: 350, totalScore: 730, goldMedals: 2, silverMedals: 2, bronzeMedals: 1 },
  { grade: 2, blueScore: 490, whiteScore: 440, totalScore: 930, goldMedals: 3, silverMedals: 2, bronzeMedals: 3 },
  { grade: 3, blueScore: 540, whiteScore: 560, totalScore: 1100, goldMedals: 4, silverMedals: 4, bronzeMedals: 2 },
];

export const INITIAL_CLASS_RANKINGS: ClassRanking[] = [
  { rank: 1, grade: 3, classNum: 1, color: 'blue', score: 380, wins: 4, losses: 0 },
  { rank: 2, grade: 3, classNum: 4, color: 'white', score: 350, wins: 3, losses: 1 },
  { rank: 3, grade: 2, classNum: 2, color: 'blue', score: 310, wins: 3, losses: 0 },
  { rank: 4, grade: 2, classNum: 5, color: 'white', score: 290, wins: 2, losses: 1 },
  { rank: 5, grade: 1, classNum: 3, color: 'blue', score: 270, wins: 2, losses: 1 },
  { rank: 6, grade: 1, classNum: 6, color: 'white', score: 240, wins: 2, losses: 1 },
  { rank: 7, grade: 3, classNum: 2, color: 'blue', score: 220, wins: 1, losses: 2 },
  { rank: 8, grade: 2, classNum: 1, color: 'blue', score: 200, wins: 1, losses: 1 },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'p-1',
    title: '3학년 축구 결승 슛 들어가는 순간 소리질렀다!!',
    content: '1반 골키퍼 선방쇼에 4반 중거리슛까지.. 프로축구 직관하는 줄 알았습니다. 양팀 다 끝까지 파이팅!',
    author: '3학년 열혈팬',
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    likes: 38,
  },
  {
    id: 'p-2',
    title: '2학년 피구 명경기 인정합니다',
    content: '마지막 1명 끝까지 피하던 거 진짜 멋있었어요. 체육대회 인생 피구 경기였습니다.',
    author: '2반 에이스',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    likes: 29,
  },
  {
    id: 'p-3',
    title: '오후 계주 출전 선수들 집합 공지 (본부석)',
    content: '오후 3시 40분까지 각 반 계주 주자(남2, 여2)는 본부석 앞으로 집합하여 번호표를 수령하세요.',
    author: '체육교사 김무선',
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    likes: 47,
  },
  {
    id: 'p-4',
    title: '청군 역전 가자아아아 🔥',
    content: '현재 총점 청군 1410 vs 백군 1350! 계주 이기면 우리가 종합 우승이다!',
    author: '청군 응원단',
    created_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    likes: 52,
  },
];

export const INITIAL_RANKINGS: RankingItem[] = [
  { id: 'r-1', nickname: '3학년 1반 (청군)', score: 380, played_at: new Date().toISOString() },
  { id: 'r-2', nickname: '3학년 4반 (백군)', score: 350, played_at: new Date().toISOString() },
  { id: 'r-3', nickname: '2학년 2반 (청군)', score: 310, played_at: new Date().toISOString() },
  { id: 'r-4', nickname: '2학년 5반 (백군)', score: 290, played_at: new Date().toISOString() },
  { id: 'r-5', nickname: '1학년 3반 (청군)', score: 270, played_at: new Date().toISOString() },
  { id: 'r-6', nickname: '1학년 6반 (백군)', score: 240, played_at: new Date().toISOString() },
];
