import { SportCategory, Match, GradeScore, ClassRanking, Post, RankingItem } from './types';

export const SPORT_CATEGORIES: SportCategory[] = [
  { id: 'soccer', name: '축구', iconName: 'Trophy', category: '구기종목', totalPoints: 150, description: '전/후반 각 20분 11인제 축구 대진' },
  { id: 'basketball', name: '농구', iconName: 'Dumbbell', category: '구기종목', totalPoints: 120, description: '전반 15분 후반 15분 5대5 코트전' },
  { id: 'dodgeball', name: '피구', iconName: 'Flame', category: '구기종목', totalPoints: 100, description: '남녀 혼성 15인 피구 서바이벌' },
  { id: 'relay', name: '이어달리기(계주)', iconName: 'Zap', category: '육상', totalPoints: 200, description: '4x100m 학년/학급 대표 계주' },
  { id: 'tug_of_war', name: '줄다리기', iconName: 'Users', category: '민속/단체', totalPoints: 150, description: '30인 단체 3판 2선승제 파워 매치' },
  { id: 'badminton', name: '배드민턴', iconName: 'Activity', category: '구기종목', totalPoints: 80, description: '복식 토너먼트 21점 3세트제' },
  { id: 'esports', name: 'e스포츠(롤)', iconName: 'Gamepad2', category: 'e스포츠', totalPoints: 100, description: '소환사의 협곡 5:5 단판 승부' },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'm-1',
    sport: 'soccer',
    round: '결승',
    teamA: { name: '3학년 1반', grade: 3, classNum: 1 },
    teamB: { name: '3학년 4반', grade: 3, classNum: 4 },
    scoreA: 2,
    scoreB: 1,
    status: 'in_progress',
    time: '14:30',
    court: '중앙 대운동장 A코트',
    pointsForWinner: 150,
  },
  {
    id: 'm-2',
    sport: 'basketball',
    round: '결승',
    teamA: { name: '2학년 2반', grade: 2, classNum: 2 },
    teamB: { name: '2학년 7반', grade: 2, classNum: 7 },
    scoreA: 34,
    scoreB: 32,
    status: 'in_progress',
    time: '14:40',
    court: '실내 체육관 1층',
    pointsForWinner: 120,
  },
  {
    id: 'm-3',
    sport: 'dodgeball',
    round: '결승',
    teamA: { name: '1학년 3반', grade: 1, classNum: 3 },
    teamB: { name: '1학년 5반', grade: 1, classNum: 5 },
    scoreA: 15,
    scoreB: 8,
    status: 'completed',
    winnerTeam: 'teamA',
    time: '13:00',
    court: '보조 운동장 C구역',
    pointsForWinner: 100,
  },
  {
    id: 'm-4',
    sport: 'relay',
    round: '결승',
    teamA: { name: '3학년 1반', grade: 3, classNum: 1 },
    teamB: { name: '2학년 2반', grade: 2, classNum: 2 },
    scoreA: 0,
    scoreB: 0,
    status: 'scheduled',
    time: '16:00 (피날레)',
    court: '중앙 트랙',
    pointsForWinner: 200,
  },
  {
    id: 'm-5',
    sport: 'tug_of_war',
    round: '4강',
    teamA: { name: '2학년 5반', grade: 2, classNum: 5 },
    teamB: { name: '2학년 1반', grade: 2, classNum: 1 },
    scoreA: 2,
    scoreB: 0,
    status: 'completed',
    winnerTeam: 'teamA',
    time: '11:20',
    court: '운동장 특설무대 앞',
    pointsForWinner: 100,
  },
  {
    id: 'm-6',
    sport: 'badminton',
    round: '4강',
    teamA: { name: '3학년 6반', grade: 3, classNum: 6 },
    teamB: { name: '3학년 2반', grade: 3, classNum: 2 },
    scoreA: 21,
    scoreB: 19,
    status: 'completed',
    winnerTeam: 'teamA',
    time: '10:40',
    court: '체육관 B코트',
    pointsForWinner: 80,
  },
  {
    id: 'm-7',
    sport: 'esports',
    round: '결승',
    teamA: { name: '3학년 3반', grade: 3, classNum: 3 },
    teamB: { name: '2학년 4반', grade: 2, classNum: 4 },
    scoreA: 1,
    scoreB: 0,
    status: 'in_progress',
    time: '15:10',
    court: '컴퓨터실 및 방송실 중계',
    pointsForWinner: 100,
  },
  {
    id: 'm-8',
    sport: 'dodgeball',
    round: '4강',
    teamA: { name: '1학년 1반', grade: 1, classNum: 1 },
    teamB: { name: '1학년 2반', grade: 1, classNum: 2 },
    scoreA: 12,
    scoreB: 10,
    status: 'completed',
    winnerTeam: 'teamA',
    time: '10:00',
    court: '보조 운동장 B구역',
    pointsForWinner: 80,
  },
];

// 학년별 총점 (1학년 5팀, 2학년 7팀, 3학년 6팀)
export const INITIAL_GRADE_SCORES: GradeScore[] = [
  { grade: 1, totalScore: 970, goldMedals: 2, silverMedals: 2, bronzeMedals: 1, classesCount: 5 },
  { grade: 2, totalScore: 1470, goldMedals: 3, silverMedals: 3, bronzeMedals: 3, classesCount: 7 },
  { grade: 3, totalScore: 1430, goldMedals: 4, silverMedals: 3, bronzeMedals: 2, classesCount: 6 },
];

// 총 18개 학급 종합 순위표 (1학년 1~5반, 2학년 1~7반, 3학년 1~6반)
export const INITIAL_CLASS_RANKINGS: ClassRanking[] = [
  { rank: 1, grade: 3, classNum: 1, score: 380, wins: 4, losses: 0 },
  { rank: 2, grade: 2, classNum: 2, score: 350, wins: 3, losses: 1 },
  { rank: 3, grade: 3, classNum: 4, score: 320, wins: 3, losses: 1 },
  { rank: 4, grade: 1, classNum: 3, score: 290, wins: 3, losses: 1 },
  { rank: 5, grade: 2, classNum: 7, score: 270, wins: 2, losses: 1 },
  { rank: 6, grade: 3, classNum: 6, score: 250, wins: 2, losses: 1 },
  { rank: 7, grade: 1, classNum: 5, score: 240, wins: 2, losses: 1 },
  { rank: 8, grade: 2, classNum: 5, score: 220, wins: 2, losses: 2 },
  { rank: 9, grade: 2, classNum: 1, score: 200, wins: 2, losses: 1 },
  { rank: 10, grade: 3, classNum: 2, score: 190, wins: 1, losses: 2 },
  { rank: 11, grade: 1, classNum: 1, score: 180, wins: 1, losses: 2 },
  { rank: 12, grade: 2, classNum: 4, score: 170, wins: 1, losses: 2 },
  { rank: 13, grade: 3, classNum: 3, score: 160, wins: 1, losses: 2 },
  { rank: 14, grade: 1, classNum: 2, score: 150, wins: 1, losses: 2 },
  { rank: 15, grade: 2, classNum: 3, score: 140, wins: 1, losses: 2 },
  { rank: 16, grade: 3, classNum: 5, score: 130, wins: 1, losses: 3 },
  { rank: 17, grade: 2, classNum: 6, score: 120, wins: 0, losses: 3 },
  { rank: 18, grade: 1, classNum: 4, score: 110, wins: 0, losses: 3 },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'p-1',
    title: '3학년 1반 축구 결승 골 장면 다시 봐도 소름!!',
    content: '1반 골키퍼 선방쇼에 4반 중거리슛까지.. 양팀 다 멋진 경기 보여줘서 고맙습니다!',
    author: '3학년 학생',
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    likes: 38,
  },
  {
    id: 'p-2',
    title: '2학년 2반 vs 2학년 7반 농구 결승전 역대급 명경기!',
    content: '마지막 2점 차이 승부 실화냐 ㄷㄷ 양팀 모두 끝까지 최선을 다했습니다.',
    author: '2학년 체육부',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    likes: 31,
  },
  {
    id: 'p-3',
    title: '오후 학급 대표 계주 출전 선수 집합 공지 (본부석)',
    content: '오후 3시 40분까지 각 반 계주 주자들은 본부석 앞으로 집합하여 번호표를 수령하세요.',
    author: '체육교사',
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    likes: 47,
  },
  {
    id: 'p-4',
    title: '현재 종합 1위 3학년 1반, 2위 2학년 2반 바짝 추격 중 🔥',
    content: '점수 차이가 30점밖에 안 나네요. 남은 계주와 줄다리기에서 종합 우승이 결정됩니다!',
    author: '무선중 방송반',
    created_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    likes: 54,
  },
];

export const INITIAL_RANKINGS: RankingItem[] = [
  { id: 'r-1', nickname: '3학년 1반', score: 380, played_at: new Date().toISOString() },
  { id: 'r-2', nickname: '2학년 2반', score: 350, played_at: new Date().toISOString() },
  { id: 'r-3', nickname: '3학년 4반', score: 320, played_at: new Date().toISOString() },
  { id: 'r-4', nickname: '1학년 3반', score: 290, played_at: new Date().toISOString() },
  { id: 'r-5', nickname: '2학년 7반', score: 270, played_at: new Date().toISOString() },
  { id: 'r-6', nickname: '3학년 6반', score: 250, played_at: new Date().toISOString() },
  { id: 'r-7', nickname: '1학년 5반', score: 240, played_at: new Date().toISOString() },
  { id: 'r-8', nickname: '2학년 5반', score: 220, played_at: new Date().toISOString() },
];
